services:
  oracle-cloud-free-tier-claimer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - oci-terraform-state:/workspace
    restart: unless-stopped

volumes:
  oci-terraform-state:
